### ISSUE TITLE
HeapByteBufferR not Usable

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket-java#19]
The underlying Agrona code has a hard time with HeapByteBufferR (read-only view) that I tried to use:

```
java.lang.ClassCastException: java.nio.HeapByteBufferR cannot be cast to sun.nio.ch.DirectBuffer
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:732)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:713)
	at io.reactivesocket.internal.FrameFlyweight.encode(FrameFlyweight.java:141)
```

**Comment by benjchristensen** [comment]
Not an issue.
