### ISSUE TITLE
Server gets into weird state after sending ERROR frame.

### ISSUE THREAD

**Issue by somasun** [ReactiveSocket/reactivesocket-java#273]
Sample code - https://gist.github.com/somasun/ac95a84c43fdd8ac06c703f4161e5d6e

The code works well for
```
                    //  return Mono.error(new Throwable());
                    return Mono.just(p);
```

But the server gets into a weird state for
```
                    return Mono.error(new Throwable());
                    // return Mono.just(p); 
```

For the second case the server prints the exception in Throwable() and fails to process subsequent frames.  An exception 'reactor.core.Exceptions$CancelException: The subscriber has denied dispatching' is raised for the subsequent frames.

**Comment by yschimke** [comment]
A couple of points

- the server is fine for new connections, but the current reactivesocket connection is effectively half closed
- It looks like in ClientServerInputMultiplexer the client MonoProcessor<Flux<Frame>> is getting cancelled due to the application error in the Mono<Payload>, then the source.receive().groupBy is sending a duplicate CLIENT group.

```
Exception observed is 34 [reactor-tcp-nio-7] WARN io.netty.channel.AbstractChannelHandlerContext  - An exception 'reactor.core.Exceptions$CancelException: The subscriber has denied dispatching' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
reactor.core.Exceptions$CancelException: The subscriber has denied dispatching
	at reactor.core.Exceptions.failWithCancel(Exceptions.java:129)
	at reactor.core.publisher.Operators.onNextDropped(Operators.java:307)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:288)
	at io.reactivesocket.internal.ClientServerInputMultiplexer.lambda$new$1(ClientServerInputMultiplexer.java:85)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:132)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.drainLoop(FluxGroupBy.java:396)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.drain(FluxGroupBy.java:332)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.onNext(FluxGroupBy.java:212)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:204)
	at reactor.ipc.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:319)
	at reactor.ipc.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:312)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yschimke** [comment]
I think the fix is something like 

https://github.com/ReactiveSocket/reactivesocket-java/pull/274/files

**Comment by robertroeser** [comment]
@yschimke think this is fixed now. Can we close the issue?

**Comment by mitermayer** [comment]
do we have a released version with this fix ?
